replicaCount: 1
 
fullnameOverride: nginx
 
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
 
imagePullSecrets: []
 
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
 
resources: {}
 
nodeSelector: {}
tolerations: []
affinity: {}

config: |
  server {
    listen 8080;

    location /api/v1/movies {
      proxy_pass http://movie-service/api/v1/movies;
    }

    location /api/v1/casts {
      proxy_pass http://cast-service/api/v1/casts;
    }
  }
