apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
